import React, { ReactNode } from "react";

import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import CssBaseline from "@mui/material/CssBaseline";

import "./globals.scss";

const roboto = Roboto({
	weight: ["300", "400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	console.log("as");
	return (
		<html lang="en">
			<AppRouterCacheProvider>
				<CssBaseline />
				<body className={roboto.className}>{children}</body>
			</AppRouterCacheProvider>
		</html>
	);
}
