import React, { ReactNode } from "react";

import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { ThemeProvider } from "next-themes";
import { Roboto, Vollkorn } from "next/font/google";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import CssBaseline from "@mui/material/CssBaseline";

import CoAppBar from "@/components/CoAppBar/CoAppBar";

import StoreProvider from "@/providers/StoreProvider";

import styles from "@/app/layout.module.scss";
import "@/styles/main.scss";

const roboto = Roboto({
	weight: ["300", "400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
});

const vollkorn = Vollkorn({
	weight: ["400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function LocaleLayout({
	children,
}: {
	children: ReactNode;
	params: { locale: string };
}) {
	const locale = await getLocale();
	const messages = await getMessages();

	return (
		<html lang={locale} suppressHydrationWarning className={roboto.className}>
			<AppRouterCacheProvider>
				<CssBaseline />
				<StoreProvider>
					<NextIntlClientProvider messages={messages}>
						<body className={vollkorn.className}>
							<ThemeProvider>
								<div className={styles.mainLayout}>
									<CoAppBar />
									<main className={styles.main}>{children}</main>
								</div>
							</ThemeProvider>
						</body>
					</NextIntlClientProvider>
				</StoreProvider>
			</AppRouterCacheProvider>
		</html>
	);
}
