export const FORM_FIELD = {
  URL: "url",
  TEXT: "text",
  SSID: "ssid",
  PASSWORD: "password",
  ENCRYPTION: "encryption",
  WIFI_HIDDEN: "wifi_hidden",
  EMAIL: "email",
  PHONE: "phone",
  LATITUDE: "lat",
  LONGITUDE: "lng",
  FIRST_NAME: "first_name",
  LAST_NAME: "last_name",
  COMPANY: "company",
  JOB_TITLE: "job_title",
} as const;
