import React, { ReactNode } from "react";

import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Roboto, Vollkorn } from "next/font/google";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import CssBaseline from "@mui/material/CssBaseline";

import CoAppBar from "@/components/CoAppBar/CoAppBar";

import StoreProvider from "@/providers/StoreProvider";
import ThemeProvider from "@/providers/ThemeProvider";

import styles from "@/app/[locale]/layout.module.scss";
import "@/styles/main.scss";

const roboto = Roboto({
	weight: ["300", "400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
});

const vollkorn = Vollkorn({
	weight: ["400", "500", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function LocaleLayout({
	children,
	params: { locale },
}: {
	children: ReactNode;
	params: { locale: string };
}) {
	const messages = await getMessages();

	return (
		<html lang={locale} className={roboto.className}>
			<AppRouterCacheProvider>
				<CssBaseline />
				<StoreProvider>
					<NextIntlClientProvider messages={messages}>
						<ThemeProvider>
							<body className={vollkorn.className}>
								<div className={styles.mainLayout}>
									<CoAppBar />
									<main>{children}</main>
								</div>
							</body>
						</ThemeProvider>
					</NextIntlClientProvider>
				</StoreProvider>
			</AppRouterCacheProvider>
		</html>
	);
}
